# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_uiS9bk5XwkYRTYn8Dphbfc19CgpYRZh
"""

# operator
# symbol =>task execute
# arithmatic operator
10/2

10//2

20.0+25

11%2

5**2

2*5+6/3+2-1

1.0+2

# comparsion (relational)
10>5
# >,< . >= , == ,! =
10==15

x=10
x=x+5
print(x)

x=10
x+=5
print(x)
# +=, /=

x=4
x**=3
print(x)

# logical operator and / or / not
x=10
x>5
y=6
y>x

x>5 or y>x

# arithmatic, logical, comprasion, assigment
# membership and identify

# membership
"p" in "jaipur"

"z"  not in "jaipur"

# identity operator
# object => class belong
# variable data type
# is=> identity operator
x=10
type(x) is int

x=10
type (x) is not str

# conditional statement (operatore)
'''
if(condition){
  statement
}
if(condition):
  print("hello")
  '''

age=19
if(age==18):
  print("Age is 18")
else:
    print("condition is false")

age=40
if(age>=18 and age<=30):
  print("age is for adult")
else:
    print("condition is false")

# age>5 => aadhar
# verma => country => India => ration card

age=4
country="India"
if(age>=5):
  print("aadar card milega")

elif(country=="India"):
  print("Ration card milega")
else:
  print("nhi milega")

a=5
b=33
c=4
if(a<b and a<c):
  print("a is smaller")
elif(b<c and b<a):
  print("b is smaller")
else:
    print("c is smaller")

if ( "i" in "tushar")

# age >18
# voter id => vote
age=17
voterid=1
if(age>=18):
  print("eligible for voting ")
  if(voterid==1):
    print("can vote")
else:
      print("can 't vote")

#xyz
#tushar
# hye tushar isha ouhc